[project]
name = "mse-pi-watch-water-resistance"
version = "0.1.0"
description = "A Python package for monitoring water resistance of MSE Pi Watch devices."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dwfpy>=1.2.0",
    "matplotlib>=3.10.8",
    "pyqt6>=6.10.2",
    "pyside6>=6.10.1",
]

[tool.uv]
package = true

[tool.ruff]
select = ["FIX002",
    "E", "F"
]

[project.scripts]
example-ad3 = "examples.example_ad3:main"
